[github]
owner = "jeremybanka"
repo = "puggers"

[changes]
ignore_conventional_commits = true

[package]
name = "puggers"
changelog = "CHANGELOG.md"
versioned_files = [
  "Cargo.toml",
  { path = "crates/puggers-cli/Cargo.toml", dependency = "puggers-core" },
  { path = "Cargo.lock", dependency = "puggers-core" },
  { path = "Cargo.lock", dependency = "puggers" },
  { path = "Cargo.lock", dependency = "dprint-plugin-pug" },
]
scopes = ["puggers", "puggers-core", "dprint-plugin-pug"]

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "version"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -C knope/release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin knope/release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: prepare release $version"

[workflows.steps.body]
template = "This PR was created by Knope. Merging it will publish the new release.\n\n$changelog"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"
