[package]
name = "dprint-plugin-pug"
version.workspace = true
edition = "2024"
description = "A super minimal Pug formatter plugin for dprint."
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dprint-core = { version = "=0.69.0", features = ["wasm"] }
puggers-core = { path = "../puggers-core", version = "0.1.6" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
